### ISSUE TITLE
Sensor to see if the car doors is locked or unlocked

### ISSUE THREAD

**Issue by whohencode** [mitch-dc/volkswagen_we_connect_id#73] opened 2022-10-11 20:40 UTC
**Is your feature request related to a problem? Please describe.**
My wife forgetts to lock the car all the time, would be great to se in HA the staus of the lock on the doors. It´s possible in the connect app, don´t know if it´s possible via the API.

**Describe the solution you'd like**
a sensor populated with the value of the lock status of the car doors.

**Describe alternatives you've considered**
Hav no alternativs

**Additional context**
N/A

**Comment by whohencode** [comment] 2022-10-12 10:00
Tried the we connect cli code from https://github.com/tillsteinbach/WeConnect-cli and it looks like lock status is visible

# weconnect-cli --username xxxxx@xxxxx.xxx --password xxxxxxxxxxx get /vehicles/WVGZZZxxxxxxxxxxx/domains/access/accessStatus/doorLockStatus
locked

**Comment by tsg21** [comment] 2022-10-13 20:43
This does seem like it would be a good addition!

**Comment by tsg21** [comment] 2022-10-13 20:53
When I try to run that CLI command for my ID.4, the `doorLockStatus` is not present. I wonder if this is because my car is still running the v2.4 software, and has not yet had the OTA update to 3.0?

What car and software version do you have, @whohencode ?

**Comment by whohencode** [comment] 2022-10-14 05:53
@tsg21 i have an ID.5 but also tried on ID.4 both on 3.0 and it works.

**Comment by JelleKoster** [comment] 2022-10-14 17:17
I agree the doorLockStatus would be a useful addition.

Confirmed:
With id3 on v2.4 /domains/access/accessStatus/doorLockStatus gives "not found".
A different endpoint (/nickname) does properly return the expected value, so the generic working of the API is not the issue (credentials etc.)

Note I found the VIN is case sensitive, at least through weconnect-cli.

For ease of reference, I've also attached the full list of available APIs on v2.4. It might be nice to compare with v3.0 to see what else is new, or to use to see what else might be a useful addition for the HA integration.
[VW_2.4_apis.txt](https://github.com/mitch-dc/volkswagen_we_connect_id/files/9788648/VW_2.4_apis.txt)

**Comment by tsg21** [comment] 2022-10-16 15:54
When VW deign to provide my ID.4 with 3.0 I will happily have a go at creating a PR to implement this. Until then I have no way to test.

It's almost certainly very simple, if someone who does have 3.0 wants to have a go.

**Comment by pplucky** [comment] 2022-10-22 16:39
> I'm also still waiting on 3.0. Got 2.4 right now but VW is struggling to get the OTA going.
> Will add this as soon as possible :)

I have received my id.3 with 3.1.0 from factory.

I can confirm I see the `doorLockStatus` is present if I call `weconnect-cli`.

@mitch-dc: Do you need any further information from the API response to be able to support or want/need a helping hand in testing? I have an HA test system with your custom component installed, which can be used for that purpose.

Thanks for this great component.

**Comment by FirstRulez** [comment] 2022-10-24 12:13
> > I'm also still waiting on 3.0. Got 2.4 right now but VW is struggling to get the OTA going.
> > Will add this as soon as possible :)
> 
> I have received my id.3 with 3.1.0 from factory.

Sorry for the silly question, but how do I find out which version of software the car is running? This is the screen in the car and it shows no updates... id.4 1st edition.
![image](https://user-images.githubusercontent.com/32237385/197522980-70fa6ebe-935e-4bc3-b338-096cdde6b283.png)

**Comment by JelleKoster** [comment] 2022-10-24 12:22
@FirstRulez Build 0790 is 2.3, build 0792 is 2.4, so you're on v2.4.

Op ma 24 okt. 2022 14:14 schreef FirstRulez ***@***.***>:

**Comment by j6miranda** [comment] 2022-10-24 22:53
I confirm that  id.4 with 3.* has the doorLockStatus is present if I call weconnect-cli.

**Comment by pplucky** [comment] 2022-10-25 21:07
> When VW deign to provide my ID.4 with 3.0 I will happily have a go at creating a PR to implement this. Until then I have no way to test.
> 
> It's almost certainly very simple, if someone who does have 3.0 wants to have a go.

Would you be willing to help me get the Doors and Windows items to be mapped as sensors to know exactly the status of each door/window, aside from the global one?

**Comment by tsg21** [comment] 2022-10-26 09:39
@pplucky I see your PR. That seems to cover the global lock state. What help do you need?

Will be interesting to see how your change behaves with my car that does not (yet) have that feature.

**Comment by pplucky** [comment] 2022-10-26 11:47
> @pplucky I see your PR. That seems to cover the global lock state. What help do you need?
> 
> Will be interesting to see how your change behaves with my car that does not (yet) have that feature.

@tsg21 My idea was to take advantage of the additional detail provided by the API to also integrate it into HA. Something like this:
![image](https://user-images.githubusercontent.com/16407309/198018150-f051cb48-18ba-49bb-9dfd-1114c7b64a13.png)

**Comment by mitch-dc** [comment] 2022-11-02 10:40
Got confirmation that my car will get the 3.0 update asap. 
So will try to add/test all new values to the integration.

**Comment by mitch-dc** [comment] 2022-11-15 08:06
I got the 3.0 update on my car (tru OTA) one of the first cars. 
Will check all the new sensors and add them to the integration. 

1 problem I already encouter is that now with the different profiles (wich we want to use) not all sensors are available if the other user is driving. 

Lock state is one of them :(

**Comment by pplucky** [comment] 2022-11-15 08:18
Please let me know if you need a beta tester. I only have a single profile assigned.

May this be something to be handled in the [underlying library](https://github.com/tillsteinbach/WeConnect-python)?

**Comment by mitch-dc** [comment] 2022-11-15 10:48
I need to change this from binary to a normal sensor, because it can have more then 2 values:

       ```
 class LockState(Enum):
            LOCKED = 'locked'
            UNLOCKED = 'unlocked'
            INVALID = 'invalid'
            UNKNOWN = 'unknown lock state'
```

**Comment by pplucky** [comment] 2022-11-15 10:53
> I need to change this from binary to a normal sensor, because it can have more then 2 values:
> 
> ```
>  class LockState(Enum):
>             LOCKED = 'locked'
>             UNLOCKED = 'unlocked'
>             INVALID = 'invalid'
>             UNKNOWN = 'unknown lock state'
> ```

Reason why I kept it like that was to assume binary_sensor 'ON' if unlocked or 'OFF' if anything else. It's a bit limited because it doesn't provide the actual status, but maybe if you could get the binary like this
- 'LOCKED' - 'OFF'
- UNLOCKED' - 'ON'
- 'INVALID' - sensor unavailable
- 'UNKNOWN' - sensor unavailable
-

**Comment by mitch-dc** [comment] 2022-11-15 10:56
Yeah i would like that but i can't figure out how to add the sensor unavailable yet

**Comment by whohencode** [comment] 2022-11-16 08:13
This seams to be fixed now

**Closed** 2022-11-16 08:13 UTC
Labels: enhancement
