### ISSUE TITLE
Cannot install weconnect==0.54.1, weconnect==0.54.2 and weconnect==0.55.0

### ISSUE THREAD

**Issue by Chris383838** [mitch-dc/volkswagen_we_connect_id#182] opened 2023-06-06 19:35 UTC
Hallo,

We connect id -> 1.6

Home Assistant 2023.6.0b5
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230605.0 - latest

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 21:32:02 (3 occurrences)
Last logged: 21:32:11

Unable to install package weconnect>=0.54.0: ERROR: Cannot install weconnect==0.54.1, weconnect==0.54.2 and weconnect==0.55.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by ColinRobbins** [comment] 2023-06-07 12:58
Same here with...
```
Home Assistant 2023.6.0b6
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230606.0 - latest
```

**Comment by chrjsorg** [comment] 2023-06-07 19:57
Seems to be a problem with HASS 2023.6. Just got it after upgrading.

**Comment by Lucasheimer** [comment] 2023-06-07 20:09
I have the same problem since the upgrade to 2023.6.
This could be the upgrade of HA to python version 3.11 as mentioned in the release logs.

**Comment by davidwalton0** [comment] 2023-06-08 07:52
Same error here too - integration can't load after upgrading HA yesterday:

Home Assistant 2023.6.0
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230607.0 - latest

Setup failed for custom integration volkswagen_we_connect_id: Requirements for volkswagen_we_connect_id not found: ['weconnect>=0.54.0'].
07:41:52 – (ERROR) setup.py
Unable to install package weconnect>=0.54.0: ERROR: Cannot install weconnect==0.54.1, weconnect==0.54.2 and weconnect==0.55.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by sebking1971** [comment] 2023-06-08 08:37
Same here, just updated HA to latest and now cannot load this integration.

**Comment by jcsogo** [comment] 2023-06-08 10:28
The problem is actually in weconnect library, that this project depends on.
weconnect requires requests~=2.29.0
homeassistant comes with requests 2.31.0

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
weconnect 0.55.0 requires requests~=2.29.0, but you have requests 2.31.0 which is incompatible.
```

**Comment by vistalba** [comment] 2023-06-08 11:11
There is already a working version for Cupra Born which was linked in HA Community: https://github.com/daernsinstantfortress/volkswagen_we_connect_id/archive/8ceb117c78f270095da34943d1a69c3192a4ff8e.zip

May this helps to find how to get it working here too?

**Comment by estragonator** [comment] 2023-06-08 14:19
Please correct me since my knowledge about how python libraries work is very limited - but the requirement of the original weconnect lib was already updated: https://github.com/tillsteinbach/WeConnect-python/commit/c9598404c9c5d2cbb932a8b3d3a9cd0d2bce8945
There was just no new version released since version 0.55.0 which has the outdated requirement.

**Comment by TravisWilder** [comment] 2023-06-08 15:48
> Please correct me since my knowledge about how python libraries work is very limited - but the requirement of the original weconnect lib was already updated: [tillsteinbach/WeConnect-python@c959840](https://github.com/tillsteinbach/WeConnect-python/commit/c9598404c9c5d2cbb932a8b3d3a9cd0d2bce8945) There was just no new version released since version 0.55.0 which has the outdated requirement.

Hi yes ... on 23th May but there was no release after it. So it will be included in the 0.56 (which is still pending)

**Comment by estragonator** [comment] 2023-06-09 07:01
I have managed to get it working with a temporary solution until the dependencies are fixed, but I had to make my own fork of the library for it.
Then changing the manifest.json line to this (try at your own risk since I WILL delete that fork when it is not needed anymore):
"requirements": ["git+https://github.com/estragonator/WeConnect-python.git@main#weconnect==0.56.0", "ascii_magic>=2.0.0"],

**Comment by TravisWilder** [comment] 2023-06-09 07:27
There is an upgrade request already triggered: https://github.com/tillsteinbach/WeConnect-python/issues/133

**Comment by TravisWilder** [comment] 2023-06-09 07:54
@mitch-dc  please update as well .. the lib has now 0.55.1 which is supporting 0.31

**Comment by woutercoppens** [comment] 2023-06-09 08:09
@TravisWilder: that was fast. Your post was faster then I received feedback from Stein.

**Comment by TravisWilder** [comment] 2023-06-09 09:05
> Changed the value manually in the manifest.json and rebooted HA. Works perfect again ;) so if you don't want to wait, that'll fix it until a new version :)

works for me as well

**Comment by Chris383838** [comment] 2023-06-09 09:58
> ["git+https://github.com/estragonator/WeConnect-python.git@main#weconnect==0.56.0", "ascii_magic>=2.0.0"],

For me also

**Comment by wgumaa** [comment] 2023-06-09 12:51
> Changed the value manually in the manifest.json and rebooted HA. Works perfect again ;) so if you don't want to wait, that'll fix it until a new version :)

For those of us who are not so competent in this, can you provide a step by step guide?

**Comment by TravisWilder** [comment] 2023-06-09 13:22
> > Changed the value manually in the manifest.json and rebooted HA. Works perfect again ;) so if you don't want to wait, that'll fix it until a new version :)
> 
> For those of us who are not so competent in this, can you provide a step by step guide?

I used the Studio Code Server 
Open /config/custom_components/volkswagen_we_connect_id/manifest.json
change the requirements line to
"requirements": ["weconnect>=0.55.1", "ascii_magic>=2.0.0"],

**Comment by wgumaa** [comment] 2023-06-09 20:05
> > > Changed the value manually in the manifest.json and rebooted HA. Works perfect again ;) so if you don't want to wait, that'll fix it until a new version :)
> > 
> > 
> > For those of us who are not so competent in this, can you provide a step by step guide?
> 
> I used the Studio Code Server Open /config/custom_components/volkswagen_we_connect_id/manifest.json change the requirements line to "requirements": ["weconnect>=0.55.1", "ascii_magic>=2.0.0"],

Managed to do it with File Editor! Nice! Thanks!!

**Comment by davidwalton0** [comment] 2023-06-09 20:09
Me too (File Editor) - and the integration works perfectly now - until the next unexpected change!
Until then, thank you @TravisWilder 🙏 - great instructions! 👍

**Comment by flixlix** [comment] 2023-06-09 20:26
Created this [PR](https://github.com/mitch-dc/volkswagen_we_connect_id/pull/185) to fix this issue

**Comment by mitch-dc** [comment] 2023-06-19 15:00
https://github.com/mitch-dc/volkswagen_we_connect_id/releases/tag/v0.1.7


Thanks @flixlix

**Closed** 2023-06-20 06:43 UTC

**Comment by gadgetbazza** [comment] 2023-06-21 11:46
Strangely I still have this issue, albeit with HA 2023.5.4 using tag 0.1.7.

I've opened issue 187 accordingly.

Or is the answer to move up to HA 2023.6?

**Comment by TravisWilder** [comment] 2023-06-21 13:37
> 

Update to 2023.6 or stay with <0.1.7
