### ISSUE TITLE
conflicting dependencies after Update 

### ISSUE THREAD

**Issue by Chris383838** [mitch-dc/volkswagen_we_connect_id#180] opened 2023-06-01 07:22 UTC
Hello,

Version We connect -> 1.5

After Update on:
Home Assistant 2023.6.0b2
Supervisor 2023.05.0
Operating System 10.2
Frontend 20230601.0 - latest

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 09:06:46 (3 occurrences)
Last logged: 09:06:54

Unable to install package weconnect==0.54.1: ERROR: Cannot install weconnect==0.54.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Mitch73-2** [comment] 2023-06-02 06:26
I also have the same problem after update to Home Assistant 2023.6.0b2.

**Comment by daernsinstantfortress** [comment] 2023-06-02 10:15
FYI, the problem is that the version of the requests library was set to a specific version, and HA 2023.6 has changed this version, which causes an unresolvable dependency error. For the Cupra fork, I've updated the reference to permit later versions:
https://github.com/daernsinstantfortress/WeConnect-python/commit/b4ad9a8ec90319730f968cbfce7eb4f54b27aabf#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552

Obviously, there's a risk of incompatibility here in the future if HA upgrades to a future version, but hopefully it won't be an issue. Note: it's not enough to just update the reference to the new version as this breaks compatibility with HA 2023.5 and earlier.

**Comment by tsg21** [comment] 2023-06-02 21:49
This issue happens pretty much every time HA update their requests version. I'm sure that the integration will work perfectly well with whatever version of requests is installed, within reason.

It seem like there really ought to be a way to override/remove the transitive dependency, but the HA documentation doesn't seem to indicate how.

**Comment by SwannyBFC** [comment] 2023-06-08 06:49
I've also got this problem after updating to 2023.6.0 official release

**Comment by MCLMNN** [comment] 2023-06-08 11:25
Same with me. Error with dependencies after updated to latest version (2023.6.0)

**Comment by mitch-dc** [comment] 2023-06-20 06:45
Should be fixed in the latest versions

**Closed by mitch-dc** 2023-06-20 06:45 UTC
